import{a as L,S as w,b as v,i as l}from"./assets/vendor-DsRbAYL4.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))o(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&o(f)}).observe(document,{childList:!0,subtree:!0});function i(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function o(r){if(r.ep)return;r.ep=!0;const s=i(r);fetch(r.href,s)}})();const b="49318761-deb5d950ade63202697546ac6",S="https://pixabay.com/api/";async function m(t,e=1,i=15){try{const o=await L.get(S,{params:{key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,t:new Date().getTime(),page:e,per_page:i}});if(o.data.hits.length===0)throw new Error("No images found");return{images:o.data.hits,total:o.data.totalHits}}catch(o){throw console.error("Error fetching images:",o),o}}const p=document.querySelector(".gallery");function q(t){return t.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
        </a>
        <div class="info">
          <p><strong>Likes:</strong> ${e.likes}</p>
          <p><strong>Views:</strong> ${e.views}</p>
          <p><strong>Comments:</strong> ${e.comments}</p>
          <p><strong>Downloads:</strong> ${e.downloads}</p>
        </div>
      </li>
    `).join("")}function y(t,e=!1){e||(p.innerHTML=""),p.insertAdjacentHTML("beforeend",q(t)),new w(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const R=document.querySelector(".form"),E=document.querySelector(".gallery"),n=document.querySelector(".loader"),a=document.querySelector(".load-more"),d=new v({color:"red",lines:12,width:8,radius:14});let u="",c=1;const g=15;let h=0;R.addEventListener("submit",async t=>{if(t.preventDefault(),u=t.target.elements["search-text"].value.trim(),!u){l.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}E.innerHTML="",c=1,a.classList.add("hidden"),n.classList.remove("hidden"),d.spin(n),document.querySelector(".gallery").innerHTML="",n.classList.remove("hidden"),d.spin(n);try{const{images:i,total:o}=await m(u,c,g);h=o,i.length===0?l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):(y(i),g<h&&a.classList.remove("hidden"))}catch{l.error({title:"Error",message:"Something went wrong. Try again!",position:"topRight"})}finally{d.stop(),n.classList.add("hidden")}const e=Math.ceil(h/g);c<e?a.classList.remove("hidden"):l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})});function T(){const t=document.querySelector(".gallery-item");if(!t)return;const e=t.getBoundingClientRect().height;window.scrollBy({top:e*2,left:0,behavior:"smooth"})}a.addEventListener("click",async()=>{c+=1,a.classList.add("hidden"),n.classList.remove("hidden"),d.spin(n);try{const{images:t}=await m(u,c,g);t.length===0||c*g>=h?(l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),a.classList.add("hidden")):(y(t,!0),a.classList.remove("hidden"),setTimeout(T,500))}catch{l.error({title:"Error",message:"Something went wrong. Try again!",position:"topRight"})}finally{d.stop(),n.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
