import{a as L,S as w,b as v,i as l}from"./assets/vendor-DsRbAYL4.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const u of o.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&s(u)}).observe(document,{childList:!0,subtree:!0});function i(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(t){if(t.ep)return;t.ep=!0;const o=i(t);fetch(t.href,o)}})();const b="49318761-deb5d950ade63202697546ac6",S="https://pixabay.com/api/";async function h(r,e=1,i=15){try{const s=await L.get(S,{params:{key:b,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:i}});if(s.data.hits.length===0)throw new Error("No images found");return{images:s.data.hits,total:s.data.totalHits}}catch(s){throw console.error("Error fetching images:",s),s}}const m=document.querySelector(".gallery");function E(r){return r.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-link">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
        </a>
        <div class="info">
          <p><strong>Likes:</strong> ${e.likes}</p>
          <p><strong>Views:</strong> ${e.views}</p>
          <p><strong>Comments:</strong> ${e.comments}</p>
          <p><strong>Downloads:</strong> ${e.downloads}</p>
        </div>
      </li>
    `).join("")}function y(r,e=!1){e||(m.innerHTML=""),m.insertAdjacentHTML("beforeend",E(r)),new w(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const q=document.querySelector(".form"),P=document.querySelector(".gallery"),n=document.querySelector(".loader"),a=document.querySelector(".load-more"),c=new v({color:"red",lines:12,width:8,radius:14});let g="",d=1;const p=15;let f=0;q.addEventListener("submit",async r=>{if(r.preventDefault(),g=r.target.elements["search-text"].value.trim(),!g){l.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}P.innerHTML="",d=1,a.classList.add("hidden"),n.classList.remove("hidden"),c.spin(n),n.classList.remove("hidden"),c.spin(n);try{const{images:e,total:i}=await h(g,d,p);f=i,e.length===0?l.error({title:"Error",message:"Sorry, no images found. Please try again!",position:"topRight"}):(y(e),p<f&&a.classList.remove("hidden"))}catch{l.error({title:"Error",message:"Something went wrong. Try again!",position:"topRight"})}finally{c.stop(),n.classList.add("hidden")}});a.addEventListener("click",async()=>{d+=1,a.classList.add("hidden"),n.classList.remove("hidden"),c.spin(n);try{const{images:r}=await h(g,d,p);r.length===0||d*p>=f?(l.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),a.classList.add("hidden")):(y(r,!0),a.classList.remove("hidden"))}catch{l.error({title:"Error",message:"Something went wrong. Try again!",position:"topRight"})}finally{c.stop(),n.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
